### ISSUE TITLE
"/a>" shows on the site

### ISSUE THREAD

**Issue by Gamerappa** [botrappa/botrappa.github.io#1]
oh fuck its gone but still i see a gap

**Comment by Mdstumpfy123** [comment]
ik fuckoff

**Comment by Gamerappa** [comment]
also wtf you limited it

**Comment by Mdstumpfy123** [comment]
lol

**Comment by Gamerappa** [comment]
I AM PROTO YOUR SECURITY IS MY MOTTO

**Comment by Mdstumpfy123** [comment]
fuck off
ur spamming my emails

**Comment by Gamerappa** [comment]
wait everytime i write some shit i spam your email


fuck

**Comment by Mdstumpfy123** [comment]
lol

**Comment by Mdstumpfy123** [comment]
still can comment

**Comment by Gamerappa** [comment]
allow me to edit

**Comment by Mdstumpfy123** [comment]
lol no

**Comment by Gamerappa** [comment]
fuck

then why blue the fox gived me permission to edit the gamerappa.ga site then?
